/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoServerFnRouteImport } from './routes/demo/server-fn'
import { Route as DemoProfileRouteImport } from './routes/demo/profile'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoServerFnRoute = DemoServerFnRouteImport.update({
  id: '/server-fn',
  path: '/server-fn',
  getParentRoute: () => DemoRoute,
} as any)
const DemoProfileRoute = DemoProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/profile': typeof DemoProfileRoute
  '/demo/server-fn': typeof DemoServerFnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/profile': typeof DemoProfileRoute
  '/demo/server-fn': typeof DemoServerFnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/profile': typeof DemoProfileRoute
  '/demo/server-fn': typeof DemoServerFnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo' | '/demo/profile' | '/demo/server-fn'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/demo/profile' | '/demo/server-fn'
  id: '__root__' | '/' | '/demo' | '/demo/profile' | '/demo/server-fn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/server-fn': {
      id: '/demo/server-fn'
      path: '/server-fn'
      fullPath: '/demo/server-fn'
      preLoaderRoute: typeof DemoServerFnRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/profile': {
      id: '/demo/profile'
      path: '/profile'
      fullPath: '/demo/profile'
      preLoaderRoute: typeof DemoProfileRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoProfileRoute: typeof DemoProfileRoute
  DemoServerFnRoute: typeof DemoServerFnRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoProfileRoute: DemoProfileRoute,
  DemoServerFnRoute: DemoServerFnRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
