/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExerciseRouteImport } from './routes/exercise'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExerciseIndexRouteImport } from './routes/exercise/index'
import { Route as DemoWithLoaderRouteImport } from './routes/demo/with-loader'
import { Route as DemoSuspenseRouteImport } from './routes/demo/suspense'
import { Route as ExerciseUsersUserIdRouteImport } from './routes/exercise/users.$userId'
import { Route as ExerciseUsersUserIdSolutionRouteImport } from './routes/exercise/users_.$userId.solution'

const ExerciseRoute = ExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciseIndexRoute = ExerciseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExerciseRoute,
} as any)
const DemoWithLoaderRoute = DemoWithLoaderRouteImport.update({
  id: '/with-loader',
  path: '/with-loader',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSuspenseRoute = DemoSuspenseRouteImport.update({
  id: '/suspense',
  path: '/suspense',
  getParentRoute: () => DemoRoute,
} as any)
const ExerciseUsersUserIdRoute = ExerciseUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => ExerciseRoute,
} as any)
const ExerciseUsersUserIdSolutionRoute =
  ExerciseUsersUserIdSolutionRouteImport.update({
    id: '/users_/$userId/solution',
    path: '/users/$userId/solution',
    getParentRoute: () => ExerciseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/exercise': typeof ExerciseRouteWithChildren
  '/demo/suspense': typeof DemoSuspenseRoute
  '/demo/with-loader': typeof DemoWithLoaderRoute
  '/exercise/': typeof ExerciseIndexRoute
  '/exercise/users/$userId': typeof ExerciseUsersUserIdRoute
  '/exercise/users/$userId/solution': typeof ExerciseUsersUserIdSolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/demo/suspense': typeof DemoSuspenseRoute
  '/demo/with-loader': typeof DemoWithLoaderRoute
  '/exercise': typeof ExerciseIndexRoute
  '/exercise/users/$userId': typeof ExerciseUsersUserIdRoute
  '/exercise/users/$userId/solution': typeof ExerciseUsersUserIdSolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/exercise': typeof ExerciseRouteWithChildren
  '/demo/suspense': typeof DemoSuspenseRoute
  '/demo/with-loader': typeof DemoWithLoaderRoute
  '/exercise/': typeof ExerciseIndexRoute
  '/exercise/users/$userId': typeof ExerciseUsersUserIdRoute
  '/exercise/users_/$userId/solution': typeof ExerciseUsersUserIdSolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/exercise'
    | '/demo/suspense'
    | '/demo/with-loader'
    | '/exercise/'
    | '/exercise/users/$userId'
    | '/exercise/users/$userId/solution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/demo/suspense'
    | '/demo/with-loader'
    | '/exercise'
    | '/exercise/users/$userId'
    | '/exercise/users/$userId/solution'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/exercise'
    | '/demo/suspense'
    | '/demo/with-loader'
    | '/exercise/'
    | '/exercise/users/$userId'
    | '/exercise/users_/$userId/solution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  ExerciseRoute: typeof ExerciseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exercise': {
      id: '/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof ExerciseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercise/': {
      id: '/exercise/'
      path: '/'
      fullPath: '/exercise/'
      preLoaderRoute: typeof ExerciseIndexRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/demo/with-loader': {
      id: '/demo/with-loader'
      path: '/with-loader'
      fullPath: '/demo/with-loader'
      preLoaderRoute: typeof DemoWithLoaderRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/suspense': {
      id: '/demo/suspense'
      path: '/suspense'
      fullPath: '/demo/suspense'
      preLoaderRoute: typeof DemoSuspenseRouteImport
      parentRoute: typeof DemoRoute
    }
    '/exercise/users/$userId': {
      id: '/exercise/users/$userId'
      path: '/users/$userId'
      fullPath: '/exercise/users/$userId'
      preLoaderRoute: typeof ExerciseUsersUserIdRouteImport
      parentRoute: typeof ExerciseRoute
    }
    '/exercise/users_/$userId/solution': {
      id: '/exercise/users_/$userId/solution'
      path: '/users/$userId/solution'
      fullPath: '/exercise/users/$userId/solution'
      preLoaderRoute: typeof ExerciseUsersUserIdSolutionRouteImport
      parentRoute: typeof ExerciseRoute
    }
  }
}

interface DemoRouteChildren {
  DemoSuspenseRoute: typeof DemoSuspenseRoute
  DemoWithLoaderRoute: typeof DemoWithLoaderRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoSuspenseRoute: DemoSuspenseRoute,
  DemoWithLoaderRoute: DemoWithLoaderRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface ExerciseRouteChildren {
  ExerciseIndexRoute: typeof ExerciseIndexRoute
  ExerciseUsersUserIdRoute: typeof ExerciseUsersUserIdRoute
  ExerciseUsersUserIdSolutionRoute: typeof ExerciseUsersUserIdSolutionRoute
}

const ExerciseRouteChildren: ExerciseRouteChildren = {
  ExerciseIndexRoute: ExerciseIndexRoute,
  ExerciseUsersUserIdRoute: ExerciseUsersUserIdRoute,
  ExerciseUsersUserIdSolutionRoute: ExerciseUsersUserIdSolutionRoute,
}

const ExerciseRouteWithChildren = ExerciseRoute._addFileChildren(
  ExerciseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  ExerciseRoute: ExerciseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
